### PR TITLE
fix: landing page most critical issues

### LINKED ISSUE #31: Version dropdown acting as link in dense mode
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

The version dropdown acts as a link to the main page when on the dense header layout(e.g. scrolled down a bit) so you can't use the dropdown when you click on it, but instead get sent to the main page for no reason

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

Docs

### PR DESCRIPTION
**Pull request by n05la3**
Closes: #31, #34, #37, #38, #42, #39, #46, #48, #52, #53, #54, #61, #63, #65, #70, #79, #78, #80, #48, #70

### CODE REVIEW

File: docs/src/layouts/DocLayout.vue [hunk 1]
```diff
@@ -76,7 +76,7 @@ export default {
     const $q = useQuasar()
     const $route = useRoute()
     const headerScrollData = ref()
-    const HEADER_SCROLL_OFFSET = 100 // number of pixels of scroll before firing a possible header scroll
+    const HEADER_SCROLL_OFFSET = 64 // number of pixels of scroll before firing a possible header scroll
```
Comment (IlCallo) [inline docs/src/layouts/DocLayout.vue]: This should be shared between the layout and the main layout header, we need to put it into a secondary file imported by both components

File: docs/src/pages/landing-page/Index.vue [hunk 2]
```diff
@@ -29,13 +29,18 @@
...
 
       <div class="intro-section__sponsors-heading q-mt-xl text-weight-bold text-lp-primary text-size-16 text-capitalize">Our Platinum sponsors</div>
-      <q-img
-        v-for="(src, index) in sponsorLogos.platinum"
-        :key="index"
-        :src="`sponsor-logos/${src}`"
-        width="200px"
-        class="q-my-md"
-      />
+      <a
```
Comment (IlCallo) [inline docs/src/pages/landing-page/Index.vue]: Can we create a "SponsorLink" component and use it every time a sponsor logo is shown?

File: docs/src/pages/landing-page/Index.vue [hunk 3]
```diff
@@ -281,7 +294,7 @@ q {
   margin-top: 200px;
 
   @media screen and (min-width: $breakpoint-md-max) {
-    height: 18vh;
+    height: calc(100vh - 152px);
```
Comment (IlCallo) [inline docs/src/pages/landing-page/Index.vue]: Can you document where this `152` comes from?

File: docs/src/pages/landing-page/Index.vue [hunk 4]
```diff
@@ -298,4 +311,9 @@ q {
     }
   }
 }
+
+:deep(.q-btn--outline:before) {
```
Comment (IlCallo) [inline docs/src/pages/landing-page/Index.vue:304]: Always document these kind of rules, explaining why you used a `:deep` selector (since it's usually better to avoid them)

File: docs/src/pages/landing-page/QuasarComponents.vue [hunk 5]
```diff
@@ -180,4 +182,11 @@ export default defineComponent({
   }
 }
 
+.slide-fade-enter-active {
```
Comment (IlCallo) [inline docs/src/pages/landing-page/QuasarComponents.vue:185]: Not sure what this should do, but it doesn't seem it's doing anything 🤔

**Review by IlCallo — CHANGES_REQUESTED** [review]

File: docs/src/pages/landing-page/Index.vue (hunk 4 above)
Comment (IlCallo) [reply docs/src/pages/landing-page/Index.vue:304]: Also, these buttons shouldn't have a border-radius, they must be squared, there's probably a prop to manage this directly in the component

File: docs/src/pages/landing-page/QuasarComponents.vue (hunk 5 above)
Comment (n05la3) [reply docs/src/pages/landing-page/QuasarComponents.vue:185]: It's for the ease in out animation of cards. It's actually doing something (if you increase the transition time for instance, you can see it transition slower), and overall it behaves a lot less clunky than the FadeIn Out.

File: docs/src/components/landing-page/SponsorLink.vue [hunk 6]
```diff
@@ -0,0 +1,30 @@
+<template>
+  <a
+    :href="`https://${href}`"
```
Comment (IlCallo) [inline docs/src/components/landing-page/SponsorLink.vue]: You're duplicating the `https://` here and when providing the link itself. Is the protocol actually needed? You it's usually automatically put there by the browser AFAIK

File: docs/src/pages/landing-page/QuasarComponents.vue (hunk 5 above)
Comment (IlCallo) [reply docs/src/pages/landing-page/QuasarComponents.vue:185]: Ok, let's leave this as is, but we need to revisit this again, to make it look "cooler" in some way
We'll need to ask Nick what he wants on this regard

File: docs/src/components/landing-page/SponsorLink.vue (hunk 6 above)
Comment (IlCallo) [reply docs/src/components/landing-page/SponsorLink.vue]: If it's actually needed, keep `https://` into the URLs your providing from the data structure

Eg: `https://dreamonkey.com` instead of `dreamonkey.com` and adding `https://` later on

Comment (n05la3) [reply docs/src/components/landing-page/SponsorLink.vue]: You are right, the browser will add this, and it's preferable leaving it out since their ssl certificate could expire and they go to http
